apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-teste1-production
  namespace: production
spec:
  project: default
  source:
    path: subcharts/prd/
    repoURL: https://github.com/psilva310/argocd-app-teste1.git
  destination:
    server: "https://kubernetes.default.svc"
    namespace: production