apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-teste1
  namespace: argocd
spec:
  project: default
  source:
    path: charts/prd/
    repoURL: https://github.com/psilva310/argocd-app-teste1.git
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: production
  syncPolicy:
    syncOptions:
    -  CreateNamespace=true
    automated:
      selfHeal: true
      prune: true